//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIAnsokan.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class Ansokan
    {
        public string Elevpersonnummer { get; set; }
        public string ElevFornamn { get; set; }
        public string ElevEfternamn { get; set; }
        public string Skola { get; set; }
        public string SkolArskurs { get; set; }
        public string ElevFolkbokforingsadress { get; set; }
        public string ElevPostnummer { get; set; }
        public string ElevPostadress { get; set; }
        public string Fritidshem { get; set; }
        public string Skoladress { get; set; }
        public bool SkolFritidshem { get; set; }
        public string SkolPostnummer { get; set; }
        public string SkolPostadress { get; set; }
        public string VardnadshavareEttNamn { get; set; }
        public string VardnadshavareEttTelefon { get; set; }
        public string VardnadshavareEttAdress { get; set; }
        public string VardnadshavareEttPostnummer { get; set; }
        public string VardnadshavareEttEpost { get; set; }
        public string VardnadshavareEttPostort { get; set; }
        public string VardnadshavareTwoNamn { get; set; }
        public string VardnadshavareTwoTelefon { get; set; }
        public string VardnadshavareTwoAdress { get; set; }
        public string VardnadshavareTwoPostnummer { get; set; }
        public string VardnadshavareTwoEpost { get; set; }
        public string VardnadshavareTwoPostort { get; set; }
        public string Period { get; set; }
        public bool VinterSkolskjuts { get; set; }
        public string AvstandFranSkola { get; set; }
        public string TrafikfarligSkolvag { get; set; }
        public string VaxelVisboende { get; set; }
        public string FunktionsVariation { get; set; }
        public string SarkildaOmstandigheter { get; set; }
        public string MotiveraAnsokan { get; set; }
        public string Vardnadshavarepersonnummer { get; set; }
        public Nullable<int> IdHandlaggare { get; set; }
        public Nullable<System.DateTime> DatumAvHandlaggare { get; set; }
        public System.DateTime DatumAvVardnadshavare { get; set; }
        public string BedomningAvHandlaggare { get; set; }
        public Nullable<bool> StatusAvHandlaggare { get; set; }
        public bool Fardig { get; set; }

        [IgnoreDataMember]
        public virtual Handlaggare Handlaggare { get; set; }
        [IgnoreDataMember]
        public virtual Vardnadshavare Vardnadshavare { get; set; }
    }
}
